services:
  - type: web
    name: escola-alunos
    runtime: node
    plan: free
    buildCommand: bash render-build.sh
    startCommand: bash render-start.sh
    envVars:
      - key: JAVA_VERSION
        value: "17"
