server.port=8080
spring.application.name=escola-alunos

# Perfil ativo: dev (local) ou prod (Render)
spring.profiles.active=dev

# Thymeleaf
spring.thymeleaf.mode=HTML5

# Encoding
spring.web.resources.encoding.charset=UTF-8
spring.web.resources.encoding.enabled=true
